name: Azure_Deploy

on:
  workflow_run:
    workflows: [Rust_CI]
    types: [completed]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v0
        with:
          acrName: cwhcontainerregistry
          containerAppName: cwh-basic
          resouceGroup: personal_website
